name: CD

on:
  push:
    branches:
      - "master"

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Update version in YAML
        run: sed -i 's/99.99.99+99/${{ github.run_number }}.0.0+${{ github.run_number }}/g' pubspec.yaml
      - name: Update KeyStore password in gradle properties
        run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/key.properties
      - name: Update KeyStore key password in gradle properties
        run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/key.properties
      - name: Install Flutter dependencies
        run: flutter pub get
        # Add build runner commands here if you have any
      - name: Format files
        run: flutter format --set-exit-if-changed .
      - name: Analyze files
        run: flutter analyze .
      - name: Run the tests
        run: flutter test
      - name: Build the APK
        run: flutter build apk --release --split-per-abi
      - name: Build App Bundle
        run: flutter build appbundle
      - name: Upload artifact to Github
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: ./build/app/outputs/apk/release/app-release.apk
  # CD
  deploy_android:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Update version in YAML
        run: sed -i 's/99.99.99+99/${{ github.run_number }}.0.0+${{ github.run_number }}/g' pubspec.yaml
      - name: Update KeyStore password in gradle properties
        run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/key.properties
      - name: Update KeyStore key password in gradle properties
        run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/key.properties
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build the APK
        run: flutter build apk --release --split-per-abi
      - name: Run Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: android
